### ISSUE TITLE
LiveView broken

### ISSUE THREAD

**Issue by apocalypsebg** [jasonkneen/AlloyXL#7] opened 2017-11-09 21:10 UTC
LiveView seems to stop working when using the library.... The controllers are not reloaded?

**Comment by jasonkneen** [comment] 2017-11-09 22:27
Sorry, what does "broken" and "stop working" mean? What errors do you get? Can you provide more information?

**Comment by apocalypsebg** [comment] 2017-11-09 22:59
Well either I'm doing something wrong (quite possible), but when using the library, the controllers are not being reloaded when they are changed - for example backgroundColor remains the same and etc...

**Comment by jasonkneen** [comment] 2018-10-02 06:19
Need to see a sample app demoing this as not seeing this

**Comment by jasonkneen** [comment] 2018-10-11 12:08
There's definitely something else going on here -- can you share a sample app that doesn't work so I can test?

**Comment by Topener** [comment] 2018-10-11 13:07
fyi: I'm seeing issues with Staballoy too...

**Comment by jasonkneen** [comment] 2018-10-11 13:31
just not seeing it -- able to make changes and reloads and works fine so interested to find out more / see examples

**Comment by jasonkneen** [comment] 2018-10-25 09:26
Closing as can't reproduce.

**Closed as completed by jasonkneen** 2018-10-25 09:26 UTC
